version: "3.0"
services:
  lime-app:
    image: martialblog/limesurvey:5.2.12-220131-fpm
    volumes:
      - ./upload:/var/www/html/upload
      - ./plugins:/var/www/html/plugins
      - lime:/var/www/html
    depends_on:
      - lime-db
    environment:
      - DB_HOST=lime-db
    env_file:
      - ./.env
    container_name: lime-app
  lime-web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - lime-app
    env_file:
      - ./.env
    container_name: lime-web
  lime-db:
    image: mariadb:10.6
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:3302:3306"
    container_name: lime-db

volumes:
  lime:
  db-data:
