networks:
  lime-net:
    driver: bridge

name: limesurvey

services:
  lime-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - upload-data:/var/www/html/upload
      - plugins-data:/var/www/html/plugins
      - config-data:/var/www/html/application/config
    ports:
      - "127.0.0.1:8087:80"
    depends_on:
      lime-db:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - lime-net
    container_name: lime-app
  lime-db:
    image: mariadb:12.3
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "127.0.0.1:3302:3306"
    networks:
      - lime-net
    container_name: lime-db

volumes:
  db-data:
  upload-data:
  plugins-data:
  config-data:
